#!/usr/bin/env bash
set -eu

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root" || exit 1

source_root="agent-html-skills/plugins/html-skills/skills"
target_root="skills/html-artifacts"
references_dir="$target_root/references"

if [ ! -d "$source_root" ]; then
  echo "error: missing $source_root; run git submodule update --init --recursive" >&2
  exit 1
fi

rm -rf "$target_root"
mkdir -p "$references_dir"

cat > "$target_root/SKILL.md" <<'EOF_SKILL'
---
name: html-artifacts
description: "Router for choosing HTML artifact patterns. Use when HTML would communicate better than markdown: diagrams, visual specs, data explorers, design prototypes, comparison matrices, dashboards, slides, timelines, ERDs, mind maps, or one-off interactive editors."
---

# HTML Artifacts

<!-- AUTO-GENERATED by scripts/generate-html-artifacts-skill.sh. Do not edit directly. -->

Use this skill when the user would benefit from a self-contained `.html` artifact instead of prose or markdown.

This is a router skill. Pick the closest pattern below, then read the referenced file before creating the artifact. Do not load every reference file.

## Pick A Pattern

- **Architecture/system map**: read `references/html-architecture-diagrams.md`
- **Brainstorm variants**: read `references/html-brainstorm-grid.md`
- **Code review explainer**: read `references/html-code-review.md`
- **Comparison matrix**: read `references/html-comparison-matrix.md`
- **CSV, JSON, logs, or event data explorer**: read `references/html-data-explorer.md`
- **Design prototype or tunable UI**: read `references/html-design-prototypes.md`
- **Design tokens, color, type, spacing**: read `references/html-design-tokens.md`
- **Database schema / ERD**: read `references/html-erd-explorer.md`
- **Parameter playground**: read `references/html-interactive-playground.md`
- **Mind map / concept map**: read `references/html-mind-map.md`
- **Research report / explainer / status report**: read `references/html-research-reports.md`
- **Slideshow / deck**: read `references/html-slideshow-deck.md`
- **Spec, RFC, implementation plan**: read `references/html-spec-planning.md`
- **SVG technical diagram**: read `references/html-svg-diagrams.md`
- **Throwaway editor / triage UI / annotator**: read `references/html-throwaway-editor.md`
- **Timeline / roadmap / Gantt**: read `references/html-timeline-roadmap.md`

## Interactive Artifacts

Some upstream references mention `html-skills-listen`, `Monitor`, or `__CLAUDE_SUBMIT_URL__`. Those are Claude Code plugin-specific server-mode details. Unless you know the current harness supports that exact path, use the clipboard fallback described in the upstream skill and make the artifact self-contained.

For the upstream listener details, read:

- `references/html-skills-listen.md`
- `references/html-skills-stop.md`

## Output

Write a real `.html` file and tell the user its absolute path. Keep the artifact self-contained unless the selected reference explicitly allows external CDN assets.
EOF_SKILL

for source_file in "$source_root"/*/SKILL.md; do
  skill_name="$(basename "$(dirname "$source_file")")"
  ln -s "../../../agent-html-skills/plugins/html-skills/skills/$skill_name/SKILL.md" "$references_dir/$skill_name.md"
done

if [ -f "agent-html-skills/plugins/html-skills/assets/submit-handler.js" ]; then
  mkdir -p "$target_root/assets"
  ln -s "../../../agent-html-skills/plugins/html-skills/assets/submit-handler.js" "$target_root/assets/submit-handler.js"
fi

echo "Generated $target_root"
